# Generated by Django 3.2.13 on 2022-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommweb', '0002_auto_20220810_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
