# Generated by Django 3.2.13 on 2022-08-22 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommweb', '0003_auto_20220810_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.utcnow),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default=datetime.datetime.utcnow, null=True, upload_to='image'),
        ),
    ]
