# Generated by Django 3.2.13 on 2022-08-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommweb', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
